root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /en/
        permanent: true

pokemon:
    resource: "@PokemonBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
      _locale: en|es
    defaults: { _locale: en }

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
