<?php

namespace PokemonBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HeatpointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeatpointRepository extends EntityRepository
{
}
