<?php

namespace PokemonBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PokemonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PokemonRepository extends EntityRepository
{
}
