<?php

namespace PokemonBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PokemonLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PokemonLocationRepository extends EntityRepository
{
}
